# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wawhfd', '0002_auto_20160901_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalenderEntry',
            new_name='CalendarEntry',
        ),
    ]
