"""empty message

Revision ID: af1f11c5a2fe
Revises: 45c84ccffb8a
Create Date: 2016-08-25 21:56:03.372918

"""

# revision identifiers, used by Alembic.
revision = 'af1f11c5a2fe'
down_revision = '45c84ccffb8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calender_entries')
    op.drop_table('recipes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('recipes_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='recipes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('calender_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='calender_entries_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calender_entries_pkey')
    )
    ### end Alembic commands ###
